const sherpa_onnx = require('sherpa-onnx');

export async function main() {

    /*function createOfflineTts() {
        let offlineTtsKokoroModelConfig = {
            model: './kokoro-multi-lang-v1_0/model.onnx',
            voices: './kokoro-multi-lang-v1_0/voices.bin',
            tokens: './kokoro-multi-lang-v1_0/tokens.txt',
            dataDir: './kokoro-multi-lang-v1_0/espeak-ng-data',
            dictDir: './kokoro-multi-lang-v1_0/dict',
            lexicon:
                './kokoro-multi-lang-v1_0/lexicon-us-en.txt,./kokoro-multi-lang-v1_0/lexicon-zh.txt',
            lengthScale: 1.0,
        };
        let offlineTtsModelConfig = {
            offlineTtsKokoroModelConfig: offlineTtsKokoroModelConfig,
            numThreads: 1,
            debug: 1,
            provider: 'cpu',
        };

        let offlineTtsConfig = {
            offlineTtsModelConfig: offlineTtsModelConfig,
            maxNumSentences: 1,
        };

        return sherpa_onnx.createOfflineTts(offlineTtsConfig);
    }

    const tts = createOfflineTts();
    const speakerId = 49;
    const speed = 1.0;
    const text =
        // '中英文语音合成测试。This is generated by next generation Kaldi using Kokoro without Misaki. 你觉得中英文说的如何呢？'
        '什么什么?生成wav要这么久?'

    const audio = tts.generate({text: text, sid: speakerId, speed: speed});
    tts.save('./test-kokoro-zh-en-49.wav', audio);
    console.log('Saved to test-kokoro-zh-en-49.wav successfully.');
    tts.free();*/


    function createOfflineTts() {
        let offlineTtsVitsModelConfig = {
            model: './vits-icefall-zh-aishell3/model.onnx',
            lexicon: './vits-icefall-zh-aishell3/lexicon.txt',
            tokens: './vits-icefall-zh-aishell3/tokens.txt',
            noiseScale: 0.667,
            noiseScaleW: 0.8,
            lengthScale: 1.0,
        };
        let offlineTtsModelConfig = {
            offlineTtsVitsModelConfig: offlineTtsVitsModelConfig,
            numThreads: 1,
            debug: 1,
            provider: 'cpu',
        };

        let offlineTtsConfig = {
            offlineTtsModelConfig: offlineTtsModelConfig,
            ruleFsts:
                './vits-icefall-zh-aishell3/phone.fst,./vits-icefall-zh-aishell3/date.fst,./vits-icefall-zh-aishell3/number.fst,./vits-icefall-zh-aishell3/new_heteronym.fst',
            ruleFars: './vits-icefall-zh-aishell3/rule.far',
            maxNumSentences: 1,
        };

        return sherpa_onnx.createOfflineTts(offlineTtsConfig);
    }

    const tts = createOfflineTts();
    const speakerId = 66;
    const speed = 1.0;
    const audio = tts.generate(
        {text: '3年前中国总人口是1411778724人', sid: speakerId, speed: speed});
    tts.save('./test-vits-zh.wav', audio);
    console.log('Saved to test-vits-zh.wav successfully.');
    tts.free();
}

main()
    .then(() => process.exit(0))
    .catch(error => {
        console.error(error);
        process.exit(1);
    });
